<?php
/*------------------------------------------------------------------------
 # SM Twitter - Version 1.1
 # Copyright (c) 2013 YouTech Company. All Rights Reserved.
 # @license - Copyrighted Commercial Software
 # Author: YouTech Company
 # Websites: http://www.magentech.com
-------------------------------------------------------------------------*/
$options         = $this->getConfigObject();
$theme           = $options->theme;
$limit           = $options->limit;
$href            = $options->href;
$widgets_id      = $options->widgets_id;
$pretext         = $options->pretext;
$posttext        = $options->posttext;

if( !empty($pretext) ){ ?>
	<div class="sm-twitter-pre">
		<?php echo $pretext;?>			
	</div>
<?php }?>
	<a class="twitter-timeline" href="<?php echo $href;?>" data-widget-id="<?php echo $widgets_id;?>" data-tweet-limit="<?php echo $limit;?>" width="<?php //echo $width;?>" height="<?php //echo $height;?>" data-theme="<?php echo $theme;?>"><?php //echo $footer_text;?></a>
	
	<script>
		!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");
	</script>
	
<?php if( !empty($posttext) ){?>
	<div class="sm-twitter-pos">
		<?php echo $posttext;?>			
	</div>
<?php }?>

